### PR TITLE
Israel playg 48 seperate logic from services

### PR DESCRIPTION
**Pull request by Hazannovich**
A lot of hot  new changes
all endpoints are working (except /train which I am not sure what it does)

### CODE REVIEW

**Comment by Yonatanb4** [comment]
@Hazannovich Good job!
Have you checked every route works properly?

**Comment by Hazannovich** [comment]
> @Hazannovich Good job! Have you checked every route works properly?

@Yonatanb4 Yes, except The /train endpoint which I am not sure what its suppose to do. 
its a GET request that calls [this](https://share.cleanshot.com/BcYzpbkp) function and return nothing.
we also call the same function every time we start the app [here](https://share.cleanshot.com/rwnhPDCF)

**Comment by Yonatanb4** [comment]
@Hazannovich we need to understand what /train does before merging. This is because we may cause a problem after merging.
Please speak to @aviadredis and make sure /train works properly and let me know.

**Comment by Hazannovich** [comment]
> > 
> 
> Hey @Yonatanb4 , I spoke to Aviad and it's ok, this Get Request isn't suppose to be used, The function inside it is running one time when you first run the app.

**Review by Yonatanb4 — APPROVED** [review]

**Pull request merged**
