### PR TITLE
Yotam playg 39 refine logging

### PR DESCRIPTION
**Pull request by yotam-yakovw**
Added a logger.py file containing logic for setting up a logger instance for use in any file
Used this logic for 4 files: app.py, main_flow.py, caching_manager.py, training_extractor.py

### CODE REVIEW

**Review by smartFreshBear — APPROVED** [review]
looks good! great job on the research.
I am approving, make sure you ran some basic sanity before merge

**Comment by smartFreshBear** [comment]
oh I see now u got some conflict, solve them and re-review

**Comment by yotam-yakovw** [comment]
I can't find conflicts can you check again please?

**Review by smartFreshBear — APPROVED** [review]
please next time rebase and not merge!

**Pull request merged**
